site_name: Financial Math Book
theme:
  name: material

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Home: index.md
  - Chapter 1 Diffusion Process:
      - 1.1 Martingale:
          - Martingale Representation Theorem: ch01/martingale/martingale_representation_theorem.md
          - Local Martingale: ch01/martingale/local_martingale.md
          - Martingale Representation Theorem in Depth: ch01/martingale/martingale_representation_theorem_in_depth.md
          - Stochastic Exponential: ch01/martingale/stochastic_exponential.md 
      - 1.2 Change of Measure:
          - Girsanov Theorem: ch01/change_of_measure/girsanov_theorem.md
      - 1.3  Infinitesimal Generator:
          - Infinitesimal Generator: ch01/infinitesimal_generator/infinitesimal_generator.md
          - Infinitesimal Generator and Martingale: ch01/infinitesimal_generator/infinitesimal_generator_and_martingale.md
      - 1.4 Connection to PDE:
          - Kolmogorov Equation: ch01/connection_to_pde/kolmogorov_equation.md
          - Kolmogorov Equation on Expectation: ch01/connection_to_pde/kolmogorov_equation_on_expectation.md
          - Feynman-Kac Formula: ch01/connection_to_pde/feynman_kac_formula.md 
  - Chapter 2 Black Scholes Model:
      - 2.1 Fundamental Theorem of Asset Pricing:
          - Fundamental Theorem of Asset Pricing: ch02/fundamental_theorem_of_asset_pricing/fundamental_theorem_of_asset_pricing.md
          - Separating Hyperplane Theorem: ch02/fundamental_theorem_of_asset_pricing/separating_hyperplane_theorem.md
      - 2.2 BS PDE Derivation:
          - Delta Hedging: ch02/bs_pde_derivation/delta_hedging.md
          - Martingale: ch02/bs_pde_derivation/martingale.md
          - Equilibrium: ch02/bs_pde_derivation/equilbrium.md
          - Change of Numeraire: ch02/bs_pde_derivation/change_of_numeraire.md
      - 2.3 BS PDE Solution:
          - Heat Equation: ch02/bs_pde_solution/heat_equation.md
          - Green Function: ch02/bs_pde_solution/green_function.md
          - Separation of Variables: ch02/bs_pde_solution/separation_of_variables.md
          - Similarity Solutions: ch02/bs_pde_solution/similarity_solutions.md
          - Fourier Transform: ch02/bs_pde_solution/fourier_transform.md
          - Mellin Transform: ch02/bs_pde_solution/mellin_transform.md
          - Laplace Transform (in time): ch02/bs_pde_solution/laplace_transform_in_time.md
          - Feynman-Kac Formula: ch02/bs_pde_solution/feynman_kac.md
          - Change of Numeraire: ch02/bs_pde_solution/change_of_numeraire.md
          - Viscosity Solutions: ch02/bs_pde_solution/viscosity_solutions.md




plugins:
  - search








